import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app." />
			</Head>

			<article className="flex min-h-screen flex-col">
				<section className="flex flex-grow flex-col gap-0.5 px-4 py-5">
					<h1 className="font-serif text-4xl text-neutral-900">Welcome to Next.js</h1>
					<p className="pl-1 text-base tracking-tight text-neutral-600">
						Visit{" "}
						<a
							href="https://nextjs.org"
							className="text-blue-600 outline-none hover:underline focus-visible:underline"
						>
							nextjs.org
						</a>{" "}
						to read the documentation.
					</p>
				</section>
			</article>
		</>
	);
}
